-- CyberMilo schema source of truth
--
-- Do not apply a separate webapp schema from this file.
-- The production schema for the project is:
--
--   ../supabase_schema.sql
--
-- Keeping a second full schema here caused drift between frontend docs and
-- the actual Supabase tables used by the backend seed/admin API.
