export const moduleCatalog = [
  { slug: "dashboard", name: "Dashboard", status: "In Progress" },
  { slug: "admissions", name: "Admissions CRM", status: "Completed" },
  { slug: "students", name: "Student Management", status: "Completed" },
  { slug: "attendance", name: "Attendance", status: "Completed" },
  { slug: "fees", name: "Fees & Accounts", status: "Completed" },
  { slug: "academics", name: "Academics", status: "Completed" },
  { slug: "timetable", name: "Timetable", status: "Completed" },
  { slug: "exams", name: "Exam & Result", status: "Completed" },
  { slug: "lms", name: "LMS / Online Learning", status: "Completed" },
  { slug: "communication", name: "Communication", status: "Completed" },
  { slug: "transport", name: "Transport", status: "Completed" },
  { slug: "hostel", name: "Hostel", status: "Completed" },
  { slug: "library", name: "Library", status: "Completed" },
  { slug: "hr-payroll", name: "HR & Payroll", status: "Completed" },
  { slug: "inventory", name: "Inventory & Assets", status: "Completed" },
  { slug: "reports", name: "Reports & Analytics", status: "Completed" },
  { slug: "security", name: "Security & Compliance", status: "Completed" },
  { slug: "ai-intelligence", name: "AI Intelligence", status: "Completed" }
];
